version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employee_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=9090
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=employee_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3366:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
